templatesx: &template-script-x
  - echo "common-script x"
  - echo "common-script y"

jobs:
  - name: sample-job-A
    type: runSh
    steps:
      - TASK:
          script:
            - echo "This is job A"
            - *template-script-1
            - *template-script-2
            - *template-script-x
            - echo "This is some more script"
