jobs:
  - name: sample-job-ZZ
    type: runSh
    steps:
      - IN: box-nginx-1-1-1
      - TASK:
          script:
            - echo "This is job: ZZ"
            
        
        
  - name: new_job_2
    type: runSh
    steps:
    - TASK:
        runtime:
          options:
            env:
            - test: test
      script:
      - - |
          echo hi 
