templatesx: &template-script-x
  - echo "common-script x"
  - echo "common-script y"

jobs:
  - name: sample-job-B
    type: runSh
    steps:
      - TASK:
        - script: *template-script-x
        - script: echo "This is some more script123"
     
  - name: sample-job-C
    type: runSh
    steps:
      - TASK:
          script:
            - echo "This is job C"
            - *template-script-x
