
templatestem : &template-script 
  - echo "common-script line 1"
  - echo "common-script line 2"
  - echo "common-script line 3"

jobs:
  - name: sample-job-A
    type: runSh
    steps:
      - TASK:
          script:
            - echo "This is job A"
            - *template-script
            - echo "This is some more script"
