jobs:
        
  - name: runSh-job
    type: runSh
    steps:
      - TASK: &hello
        - script: echo "hello"
        - script: echo $(shipctl get_resource_name hello_major)
        - script: echo $(shipctl bump_version 5.1.2 major)
        - script: echo $(shipctl bump_version 5.1.2 minor)
        - script: echo $(shipctl bump_version 5.1.2 patch)
        - script: echo $(shipctl bump_version v5.1.2 major)
        - script: echo $(shipctl bump_version v5.1.2 minor)
        - script: echo $(shipctl bump_version v5.1.2 patch)
        - script: echo $(shipctl bump_version v5.1.2 rc)
        - script: echo $(shipctl bump_version v5.1.2-rc rc)
        - script: echo $(shipctl bump_version v5.1.2-rc.1 rc)
        - script: echo $(shipctl bump_version v5.1.2-rc.3 final)
        - script: echo $(shipctl bump_version v5.1.2-rc.3 alpha)
        - script: echo $(shipctl bump_version v1.1.1-rc.2.beta.2 beta)
        - script: echo $(shipctl bump_version v1.1.1-beta.2.rc.2 beta)
        
  - name: runSh-job-2
    type: runSh
    steps:
      - TASK: *hello
        - script: echo "some extra stuff"
      


   
        
