jobs:
  - name: manifest-job
    type: manifest
    steps:
      - IN: box-nginx-1
      
  - name: release-job
    type: release
    bump: final
    steps:
      - IN: manifest-job
      - IN: version-resource

