vars:
  region: us-west-2   
  sourceName: aws_default_cluster
  integration: ship_int
  type: trigger

triggers:
  - name: trigger-dv-man-1
    type: ${type}
    version:
      counter: 64412345
      
  - name: tr1
    type: trigger
    version:
      counter: 2
      
      

